name: Machine Failure CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Project Files
        run: |
          python src/data_ingestion.py
          python src/data_preprocessing.py
          python src/model_training.py
          python src/model_evaluation.py
